service: FizzBurgerChallenge

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 192
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  endpointType: REGIONAL
  apiName: FizzBurgerChallenge API

custom:
  serverless-offline:
    port: 4000
    printOutput: true
    cacheInvalidationRegex: 'node_modules/'

functions:
  GetExample:
    handler: src/example/get.handler
    description: Funci칩n de ejemplo para GET. Eliminar cuando ya no se necesite m치s.
    events:
      - http:
          integration: lambda-proxy
          method: get
          path: /example
  PostExample:
    handler: src/example/post.handler
    description: Funci칩n de ejemplo para POST. Eliminar cuando ya no se necesite m치s.
    events:
      - http:
          integration: lambda-proxy
          method: post
          path: /example

plugins:
  - serverless-offline
